# Generated by Django 3.0.5 on 2020-04-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algodoeira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('producao_diaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fardoes', models.IntegerField()),
                ('rolinhos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fardoes', models.IntegerField()),
                ('rolinhos', models.IntegerField()),
                ('algodoeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.Algodoeira')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.Fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algodoeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.Algodoeira')),
            ],
        ),
    ]
